// Recipe library — Passionate Penny Pincher freezer menus + expansion pack.
// Static reference data: never changes, so it lives in code rather than
// Firebase. Only the meal-plan link (recipe id) is stored in the database.
export const RECIPES = [
 {
  "id": "quick-easy-lasagna",
  "name": "quick & easy lasagna",
  "box": "freezer",
  "week": 1,
  "category": "main",
  "dish": "pasta",
  "protein": "beef",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "1 hour",
  "serves": "12",
  "calories": 545,
  "ingredients": [
   "1 lb lean ground beef",
   "1 lb Italian sausage",
   "1 large yellow onion, chopped",
   "24 oz jar spaghetti sauce",
   "8 oz can tomato sauce",
   "3 cloves garlic, minced",
   "½ tsp salt",
   "½ tsp Italian seasoning",
   "12 lasagna noodles",
   "15 oz carton ricotta cheese",
   "½ cup Parmesan cheese, grated",
   "½ tsp dried parsley flakes",
   "3 cups mozzarella cheese,"
  ],
  "steps": [
   "In large saucepan, combine ground beef, sausage, and",
   "Meanwhile, in medium-size bowl, stir together ricotta,",
   "Lightly spray 2 (8x8-inch) disposable foil pans with cooking",
   "Cover with plastic wrap and aluminum foil. Label and freeze.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Remove foil and plastic wrap; then"
  ]
 },
 {
  "id": "pesto-tortellini-bake",
  "name": "pesto tortellini bake",
  "box": "freezer",
  "week": 1,
  "category": "main",
  "dish": "pasta",
  "protein": "chicken",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "1 hour",
  "serves": "6-8",
  "calories": 438,
  "ingredients": [
   "1 lb pkg cheese tortellini, frozen",
   "2 (15 oz) jars alfredo sauce",
   "2 cloves garlic, minced",
   "½ cup prepared pesto",
   "1 cup mozzarella cheese, shredded",
   "¼ cup Parmesan cheese, grated",
   "2 cups rotisserie chicken,"
  ],
  "steps": [
   "In large bowl, combine tortellini, alfredo sauce, garlic, pesto,",
   "Pour into greased 13x9-inch disposable foil pan. Top with",
   "To cook from frozen, preheat oven to 375°F. Remove plastic"
  ]
 },
 {
  "id": "grandmas-beef-brisket",
  "name": "grandma’s beef brisket",
  "box": "freezer",
  "week": 1,
  "category": "main",
  "dish": "skillet",
  "protein": "beef",
  "method": "oven",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "5 hours",
  "serves": "8-10",
  "calories": 341,
  "ingredients": [
   "4-5 lb boneless beef brisket",
   "2 Tbsps liquid smoke",
   "2 Tbsps Worcestershire sauce",
   "1 tsp onion salt",
   "1 tsp garlic salt",
   "1 tsp celery salt",
   "½ tsp pepper"
  ],
  "steps": [
   "Sprinkle all ingredients over brisket, rub, and wrap tightly",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Keep brisket wrapped in foil and wrap second piece of foil"
  ]
 },
 {
  "id": "lemon-pesto-chicken-tenders",
  "name": "lemon pesto chicken tenders",
  "box": "freezer",
  "week": 1,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "oven",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "4-6",
  "calories": 159,
  "ingredients": [
   "10-12 chicken tenderloins,",
   "½ cup prepared pesto",
   "3 Tbsps lemon juice",
   "½ cup mozzarella cheese, shredded"
  ],
  "steps": [
   "In gallon-size zip-top bag, combine chicken tenderloins,",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 375°F. Place chicken into 13x9-inch baking",
   "Remove foil and sprinkle cheese over top of chicken. Bake",
   "Serve with rice or over pasta with extra pesto, if desired."
  ]
 },
 {
  "id": "brunswick-stew-chicken-casserole",
  "name": "brunswick stew chicken casserole",
  "box": "freezer",
  "week": 1,
  "category": "main",
  "dish": "soup",
  "protein": "chicken",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "1 hour 15 minutes",
  "serves": "8",
  "calories": 600,
  "ingredients": [
   "1½ lb boneless, skinless chicken",
   "14 oz pkg smoked sausage, cut into",
   "3 cups frozen cubed hashbrowns",
   "12 oz pkg frozen lima beans",
   "12 oz pkg frozen vegetable",
   "14.5 oz can petite diced tomatoes",
   "1 cup barbecue sauce",
   "1 oz pkg Italian dressing mix"
  ],
  "steps": [
   "In large bowl, stir together all ingredients. Pour into 13x9-inch",
   "When ready to cook, thaw in refrigerator 1-2 days. Remove",
   "Preheat oven to 350°F. Bake, covered 1 hour or until chicken",
   "Serve with extra barbecue sauce, if desired."
  ]
 },
 {
  "id": "ranch-parmesan-chicken-tenders",
  "name": "ranch & parmesan chicken tenders",
  "box": "freezer",
  "week": 2,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "35 minutes",
  "serves": "6",
  "calories": 343,
  "ingredients": [
   "4 boneless, skinless chicken breasts",
   "1 cup panko bread crumbs",
   "½ cup Parmesan cheese, grated",
   "1 tsp garlic powder",
   "salt and pepper",
   "1 cup ranch dressing",
   "¼ cup butter, melted"
  ],
  "steps": [
   "Combine bread crumbs, Parmesan cheese, garlic powder, and",
   "Dip chicken into ranch dressing, making sure to coat both",
   "Flash freeze on baking sheet. Once frozen, move to gallon-",
   "Preheat oven to 400°F. Place thawed chicken onto greased",
   "Bake 30-35 minutes or until chicken is cooked through. Broil"
  ]
 },
 {
  "id": "sweet-spicy-salmon",
  "name": "sweet & spicy salmon",
  "box": "freezer",
  "week": 2,
  "category": "main",
  "dish": "skillet",
  "protein": "seafood",
  "method": "oven",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "20 minutes",
  "serves": "6",
  "calories": 225,
  "ingredients": [
   "2 lb salmon filet",
   "¼ cup honey",
   "2 Tbsps low-sodium soy sauce",
   "2 Tbsps teriyaki sauce",
   "1 Tbsp rice vinegar",
   "1 Tbsp sesame oil",
   "1 Tbsp squeezeable ginger",
   "3 cloves garlic, minced",
   "¼ tsp crushed red pepper",
   "green onions, for garnish (optional)"
  ],
  "steps": [
   "Add all ingredients for marinade into quart-size zip-top bag.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Combine salmon and marinade; refrigerate 30 minutes.",
   "Preheat oven to 375°F. Line baking sheet with long piece of",
   "Bake 15-20 minutes or until fish flakes easily with fork. Open",
   "Garnish with green onions, if desired."
  ]
 },
 {
  "id": "hashbrown-ham-casserole",
  "name": "hashbrown & ham casserole",
  "box": "freezer",
  "week": 2,
  "category": "main",
  "dish": "casserole",
  "protein": "pork",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "45 minutes",
  "serves": "6",
  "calories": 481,
  "ingredients": [
   "20 oz pkg refrigerated hashbrowns",
   "1½ cups Colby Jack",
   "1 cup ham, chopped",
   "4 oz can diced green chiles",
   "¼ cup green onions, sliced",
   "4 large eggs",
   "12 oz can evaporated milk",
   "¼ tsp salt",
   "¼ tsp pepper"
  ],
  "steps": [
   "Arrange potatoes in greased 13x9-inch disposable foil pan.",
   "Stir together eggs, milk, salt, and pepper. Pour egg mixture",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Bake uncovered, 45 minutes or until"
  ]
 },
 {
  "id": "hawaiian-grilled-chicken",
  "name": "hawaiian grilled chicken",
  "box": "freezer",
  "week": 2,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "20 minutes",
  "serves": "4-6",
  "calories": 422,
  "ingredients": [
   "2-3 lb boneless, skinless chicken",
   "1 cup brown sugar",
   "¾ cup ketchup",
   "1/3 cup chicken broth",
   "¾ cup low-sodium soy sauce",
   "2 cloves garlic, minced"
  ],
  "steps": [
   "In large mixing bowl, combine brown sugar, ketchup, chicken",
   "Place chicken into gallon-size zip-top bag and pour remaining",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Discard the marinade and drain chicken. Grill chicken covered"
  ]
 },
 {
  "id": "asian-beef-lettuce-wraps",
  "name": "asian beef lettuce wraps",
  "box": "freezer",
  "week": 2,
  "category": "main",
  "dish": "sandwich",
  "protein": "beef",
  "method": "stovetop",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "15 minutes",
  "serves": "4",
  "calories": 302,
  "ingredients": [
   "1 lb lean ground beef",
   "3 Tbsps honey",
   "3 Tbsps low-sodium soy sauce",
   "1 Tbsp sesame oil",
   "1 Tbsp ketchup",
   "3 green onions, chopped",
   "2 cloves garlic, minced",
   "⅛ tsp crushed red pepper",
   "1 head iceberg lettuce",
   "optional toppings: sliced green"
  ],
  "steps": [
   "Whisk all ingredients together except ground beef.",
   "In gallon-size zip-top bag, add beef and sauce; knead",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "In large skillet, cook beef mixture until browned and crumbly."
  ]
 },
 {
  "id": "sesame-honey-chicken-lettuce-wraps",
  "name": "sesame & honey chicken lettuce wraps",
  "box": "freezer",
  "week": 3,
  "category": "main",
  "dish": "sandwich",
  "protein": "chicken",
  "method": "stovetop",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "15 minutes",
  "serves": "6",
  "calories": 362,
  "ingredients": [
   "2 lb boneless, skinless chicken",
   "1/3 cup cornstarch",
   "¼ cup honey",
   "1 Tbsp soy sauce",
   "1 clove garlic, minced",
   "1 tsp sesame seeds",
   "¼ tsp crushed red pepper",
   "2-3 Tbsps canola oil",
   "1 head iceberg lettuce",
   "optional toppings: shredded"
  ],
  "steps": [
   "Add chicken and cornstarch to gallon-size zip-top bag. Knead",
   "In quart-size zip-top bag, combine remaining ingredients. Add",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "In wok or large skillet, heat canola oil over medium-high"
  ]
 },
 {
  "id": "barbecue-chicken-wings",
  "name": "barbecue chicken wings",
  "box": "freezer",
  "week": 3,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "4-5 hours",
  "serves": "8",
  "calories": 497,
  "ingredients": [
   "4 lb chicken wings, split at joints",
   "1 cup barbecue sauce",
   "¼ cup orange juice",
   "2 Tbsps honey"
  ],
  "steps": [
   "Combine all ingredients in gallon-size zip-top bag.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Remove wings from slow cooker and place onto foil-lined"
  ]
 },
 {
  "id": "food-truck-style-cuban-sandwiches",
  "name": "food truck-style cuban sandwiches",
  "box": "freezer",
  "week": 3,
  "category": "main",
  "dish": "sandwich",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "8 hours",
  "serves": "6",
  "calories": 430,
  "ingredients": [
   "2-3 lb chuck or shoulder",
   "1 large yellow onion, sliced",
   "1 green bell pepper, sliced",
   "1½ tsps ground cumin",
   "2 beef bouillon cubes",
   "1 tsp dried oregano",
   "2 cloves garlic, minced",
   "¼ cup orange juice",
   "3 tsps lime juice",
   "1 pkg hamburger buns",
   "optional toppings: provolone"
  ],
  "steps": [
   "Place all ingredients except buns and optional toppings into",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Shred meat and discard any fat.",
   "Serve on toasted buns or rolls. Add sliced provolone cheese,"
  ]
 },
 {
  "id": "sweet-barbecue-ribs",
  "name": "sweet barbecue ribs",
  "box": "freezer",
  "week": 3,
  "category": "main",
  "dish": "skillet",
  "protein": "pork",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "5-6 hours",
  "serves": "6",
  "calories": 584,
  "ingredients": [
   "2-3 lb pork country-style ribs",
   "3 cloves garlic, minced",
   "¼ cup brown sugar",
   "1 cup barbecue sauce"
  ],
  "steps": [
   "Combine all ingredients into a gallon-size zip-top bag. Label",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Serve with extra barbecue sauce, if desired."
  ]
 },
 {
  "id": "kid-friendly-pizza-meatloaf",
  "name": "kid-friendly pizza meatloaf",
  "box": "freezer",
  "week": 3,
  "category": "main",
  "dish": "skillet",
  "protein": "beef",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "1 hour 10 minutes",
  "serves": "6",
  "calories": 618,
  "ingredients": [
   "1 lb lean ground beef",
   "1 lb ground Italian sausage",
   "2 large eggs",
   "1 cup Italian bread crumbs",
   "14 oz jar pizza sauce, divided",
   "8 oz mozzarella cheese, shredded"
  ],
  "steps": [
   "In large mixing bowl, combine ground beef, Italian sausage,",
   "Shape into loaf and place into gallon-size zip-top bag. Label",
   "Reserve ½ cup pizza sauce and ½ cup cheese in 2 separate",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Remove meatloaf from zip-top bag,"
  ]
 },
 {
  "id": "cheesy-baked-spaghetti",
  "name": "cheesy baked spaghetti",
  "box": "freezer",
  "week": 4,
  "category": "main",
  "dish": "pasta",
  "protein": "beef",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6",
  "calories": 593,
  "ingredients": [
   "1 lb lean ground beef",
   "8 oz spaghetti, cooked to al dente",
   "25 oz jar spaghetti sauce",
   "1 Tbsp butter",
   "1/3 cup onions, chopped",
   "8 oz pkg cream cheese, softened",
   "2 Tbsps milk",
   "½ cup Parmesan cheese, grated",
   "1/2 cup green peppers,",
   "2.8 oz can crispy fried onions"
  ],
  "steps": [
   "In large skillet, cook ground beef until browned and crumbly;",
   "Add thin layer of spaghetti sauce to bottom of 11x7-inch",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Remove foil and plastic wrap. Bake"
  ]
 },
 {
  "id": "grilled-basil-chicken",
  "name": "grilled basil chicken",
  "box": "freezer",
  "week": 4,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "10 minutes",
  "serves": "4-6",
  "calories": 231,
  "ingredients": [
   "4-6 boneless, skinless chicken",
   "3 Tbsps red wine vinegar",
   "3 Tbsps olive oil",
   "2 Tbsps fresh basil, minced",
   "2 cloves garlic, minced",
   "¼ tsp salt",
   "¼ tsp pepper"
  ],
  "steps": [
   "In gallon-size zip-top bag, combine all ingredients.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Drain chicken, discarding marinade. Grill chicken, covered,"
  ]
 },
 {
  "id": "salsa-verde-shredded-pork",
  "name": "salsa verde shredded pork",
  "box": "freezer",
  "week": 4,
  "category": "main",
  "dish": "mexican",
  "protein": "pork",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "6-8 hours",
  "serves": "8",
  "calories": 186,
  "ingredients": [
   "2 lb boneless pork loin",
   "16 oz jar salsa verde",
   "1 large yellow onion, diced",
   "3 cloves garlic, minced",
   "1 Tbsp ground cumin",
   "¼ tsp crushed red pepper flakes",
   "¼ tsp pepper",
   "corn or flour tortillas",
   "optional toppings: shredded"
  ],
  "steps": [
   "In gallon-size zip-top bag, combine pork, salsa verde, onion,",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Transfer contents of bag to slow cooker. Cover and cook on",
   "Shred pork and mix with sauce in slow cooker. Serve over"
  ]
 },
 {
  "id": "cracker-barrel-chicken-tenderloin-sandwiches",
  "name": "cracker barrel chicken tenderloin sandwiches",
  "box": "freezer",
  "week": 4,
  "category": "main",
  "dish": "sandwich",
  "protein": "chicken",
  "method": "stovetop",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "10 minutes",
  "serves": "4",
  "calories": 459,
  "ingredients": [
   "1½ lb chicken tenderloins",
   "½ cup Italian dressing",
   "1 tsp lime juice",
   "1½ tsps honey",
   "sourdough bread",
   "lettuce",
   "tomato",
   "mayonnaise"
  ],
  "steps": [
   "Mix Italian dressing, lime juice, and honey in gallon-size zip-",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "In large, nonstick skillet, cook chicken tenderloins until done,",
   "Serve on toasted sourdough bread with lettuce, tomato,"
  ]
 },
 {
  "id": "taco-inspired-spaghetti",
  "name": "taco-inspired spaghetti",
  "box": "freezer",
  "week": 4,
  "category": "main",
  "dish": "mexican",
  "protein": "beef",
  "method": "stovetop",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "40 minutes",
  "serves": "6",
  "calories": 470,
  "ingredients": [
   "1 lb lean ground beef",
   "1 large yellow onion, chopped",
   "8 oz spaghetti noodles, uncooked",
   "1 oz pkg taco seasoning",
   "1/2 cup water",
   "15 oz can ranch-style beans",
   "10 oz can Ro- Tel tomatoes",
   "½ cup salsa",
   "8 oz Mexican-blend cheese,"
  ],
  "steps": [
   "Cook spaghetti noodles according to package directions",
   "In large skillet, cook ground beef with onions until beef is",
   "Pour mixture into greased 13x9-inch disposable foil pan. Let",
   "Cover with plastic wrap and aluminum foil. Label and freeze.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Remove from refrigerator 30 minutes prior to baking. Preheat"
  ]
 },
 {
  "id": "slow-cooker-steak-chili",
  "name": "slow cooker steak chili",
  "box": "freezer",
  "week": 5,
  "category": "main",
  "dish": "soup",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "8 hours",
  "serves": "4",
  "calories": 392,
  "ingredients": [
   "1½ lb stew beef",
   "1/2 large yellow onion, chopped",
   "15 oz can pinto beans, rinsed",
   "28 oz can petite diced tomatoes",
   "1 cup beef broth",
   "1 Tbsp chili powder",
   "2 tsps ground cumin",
   "1½ tsps garlic salt",
   "¼ tsp crushed red pepper flakes",
   "¼ tsp dried oregano",
   "¼ tsp pepper",
   "optional toppings: shredded"
  ],
  "steps": [
   "Place all ingredients into gallon-size zip-top bag. Knead gently",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Serve with optional toppings, if desired."
  ]
 },
 {
  "id": "sausage-white-bean-soup",
  "name": "sausage & white bean soup",
  "box": "freezer",
  "week": 5,
  "category": "main",
  "dish": "soup",
  "protein": "chicken",
  "method": "stovetop",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "6 hours",
  "serves": "8",
  "calories": 381,
  "ingredients": [
   "1 lb breakfast sausage",
   "3 cloves garlic, minced",
   "12 oz pkg frozen mirepoix blend",
   "2 (14 oz) cans great northern",
   "28 oz can diced tomatoes",
   "¾ tsp dried rosemary",
   "1 tsp dried oregano",
   "1 tsp dried basil",
   "32 oz carton chicken broth"
  ],
  "steps": [
   "In medium skillet, cook sausage until browned",
   "Add sausage and remaining ingredients except chicken broth",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place all contents of bag and reserved chicken broth into slow"
  ]
 },
 {
  "id": "breakfast-burritos",
  "name": "breakfast burritos",
  "box": "freezer",
  "week": 5,
  "category": "breakfast",
  "dish": "breakfast",
  "protein": "pork",
  "method": "stovetop",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "2 minutes",
  "serves": "8",
  "calories": 397,
  "ingredients": [
   "12 large eggs, beaten",
   "½ lb breakfast sausage, browned",
   "¾ cup salsa",
   "1 cup cheddar cheese, shredded",
   "8 taco-size flour tortillas",
   "hot sauce (optional)"
  ],
  "steps": [
   "In large, greased skillet, scramble eggs until cooked but still",
   "Warm tortillas in microwave about 15 seconds, until warm",
   "Distribute eggs, sausage mixture, and cheese evenly over",
   "Flash-freeze burritos in single layer on wax paper-lined",
   "When frozen, wrap each burrito in aluminum foil.",
   "To serve: Remove foil and wrap in paper towel. Heat each"
  ]
 },
 {
  "id": "sausage-cheese-quiche",
  "name": "sausage & cheese quiche",
  "box": "freezer",
  "week": 5,
  "category": "main",
  "dish": "skillet",
  "protein": "pork",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "1 hour 20 minutes",
  "serves": "6-8",
  "calories": 309,
  "ingredients": [
   "½ lb breakfast sausage",
   "5 large eggs",
   "½ cup heavy cream",
   "¼ cup milk",
   "½ tsp garlic salt",
   "1 cup cheddar cheese, shredded",
   "1 premade 9-inch deep-dish"
  ],
  "steps": [
   "In medium skillet, cook sausage until browned and crumbly;",
   "In large bowl, whisk eggs, cream, milk, and garlic salt until well",
   "Pour egg mixture into pie crust. Cover with plastic wrap and",
   "When ready to bake, preheat oven to 375°F. Remove foil and"
  ]
 },
 {
  "id": "slow-cooker-orange-chicken",
  "name": "slow cooker orange chicken",
  "box": "freezer",
  "week": 5,
  "category": "main",
  "dish": "asian",
  "protein": "meatless",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "6 hours",
  "serves": "6",
  "calories": 485,
  "ingredients": [
   "2 lb boneless, skinless",
   "1 cup orange marmalade",
   "1 cup barbecue sauce",
   "3 Tbsps soy sauce",
   "⅛ tsp crushed red pepper"
  ],
  "steps": [
   "Add chicken and remaining ingredients to gallon-size zip-top",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Pour contents of bag into slow cooker. Cover and cook on low",
   "When done, shred chicken and serve over rice, if desired."
  ]
 },
 {
  "id": "hot-chicken-salad",
  "name": "hot chicken salad",
  "box": "freezer",
  "week": 6,
  "category": "main",
  "dish": "salad",
  "protein": "chicken",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "45 minutes",
  "serves": "6",
  "calories": 688,
  "ingredients": [
   "4 cups cooked chicken, chopped",
   "10.5 oz can cream of chicken soup",
   "1 cup mayonnaise",
   "¼ cup onion, diced",
   "1½ Tbsps lemon juice",
   "1 tsp salt",
   "2 cups celery, chopped",
   "1 cup almonds, slivered",
   "2 cups cheddar cheese, shredded",
   "2 cups potato chips, crushed"
  ],
  "steps": [
   "In large mixing bowl, combine soup, mayonnaise, onion,",
   "Spoon mixture into 13x9-inch disposable foil pan. Cover",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Remove foil and plastic wrap, then"
  ]
 },
 {
  "id": "chicken-cordon-bleu-bake",
  "name": "chicken cordon bleu bake",
  "box": "freezer",
  "week": 6,
  "category": "main",
  "dish": "casserole",
  "protein": "chicken",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "55 minutes",
  "serves": "6",
  "calories": 561,
  "ingredients": [
   "4 cups cooked chicken, cubed",
   "10.5 oz can cream of chicken soup",
   "½ cup milk",
   "6 oz pkg stuffing mix",
   "½ lb deli ham, sliced and cut into",
   "½ cup Swiss cheese, shredded",
   "2 cups cheddar cheese, shredded"
  ],
  "steps": [
   "Prepare stuffing mix according to package directions. Spray",
   "Place cooked chicken into pan; layer with ham, Swiss cheese, 1",
   "Cover with plastic wrap and aluminum foil. Label and freeze.",
   "When ready to cook, thaw in refrigerator 1-2 days. Set onto",
   "Remove foil and plastic wrap, then replace foil loosely. Bake"
  ]
 },
 {
  "id": "easy-chicken-parmesan",
  "name": "easy chicken parmesan",
  "box": "freezer",
  "week": 6,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "40 minutes",
  "serves": "8",
  "calories": 383,
  "ingredients": [
   "5 cups cooked chicken, diced",
   "24 oz jar spaghetti sauce",
   "2 cups mozzarella cheese, shredded",
   "1 cup Parmesan cheese, shredded",
   "2 cups panko bread crumbs",
   "1 tsp Italian seasoning",
   "1½ tsps garlic powder",
   "3 Tbsps olive oil"
  ],
  "steps": [
   "Spray 13x9-inch disposable foil pan with cooking spray. Place",
   "Sprinkle mozzarella cheese on top of chicken, then top with",
   "In small bowl, add first three topping ingredients and stir",
   "Sprinkle bread crumb topping over Parmesan layer. Cover",
   "When ready to cook, thaw in refrigerator 1-2 days. Remove",
   "Preheat oven to 350°F. Bake 40 minutes, or until bubbly and"
  ]
 },
 {
  "id": "grilled-pork-tenderloins",
  "name": "grilled pork tenderloins",
  "box": "freezer",
  "week": 6,
  "category": "main",
  "dish": "skillet",
  "protein": "pork",
  "method": "oven",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6",
  "calories": 414,
  "ingredients": [
   "2 pork tenderloins (about 1 lb each)",
   "¼ cup honey",
   "1/3 cup low-sodium soy sauce",
   "1/3 cup teriyaki sauce",
   "3 Tbsps brown sugar",
   "1 Tbsp squeezeable ginger",
   "3 cloves garlic, minced",
   "4 tsps ketchup",
   "½ tsp onion powder",
   "½ tsp ground cinnamon",
   "¼ tsp cayenne pepper"
  ],
  "steps": [
   "In large bowl, combine all ingredients except pork tenderloins.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Drain and discard marinade from meat. Grill, covered,"
  ]
 },
 {
  "id": "ham-swiss-croissant-bake",
  "name": "ham & swiss croissant bake",
  "box": "freezer",
  "week": 6,
  "category": "main",
  "dish": "casserole",
  "protein": "pork",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "1 hour",
  "serves": "6",
  "calories": 446,
  "ingredients": [
   "8 oz ham, chopped",
   "3 large croissants",
   "1 cup Swiss cheese, shredded",
   "6 large eggs",
   "1 cup half-and-half",
   "1 Tbsp yellow mustard",
   "2 Tbsps honey",
   "¼ tsp salt",
   "¼ tsp pepper"
  ],
  "steps": [
   "Tear croissants into pieces. Place into greased 11x7-inch",
   "Whisk eggs, half-and-half, mustard, honey, salt, and pepper;",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 325°F. Remove foil and plastic wrap, then"
  ]
 },
 {
  "id": "simple-shepherds-pie",
  "name": "simple shepherd’s pie",
  "box": "freezer",
  "week": 7,
  "category": "dessert",
  "dish": "dessert",
  "protein": "none",
  "method": "stovetop",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6",
  "calories": 402,
  "ingredients": [
   "1½ lb ground beef",
   "1 large yellow onion, chopped",
   "12 oz pkg frozen peas and carrots",
   "1 pkg brown gravy mix",
   "14.5 oz can low-sodium beef broth",
   "2 Tbsps Worcestershire sauce",
   "32 oz carton refrigerated"
  ],
  "steps": [
   "In large skillet, cook ground beef and onion until beef is",
   "Heat potatoes according to package directions.",
   "Pour meat mixture into 13x9-inch disposable foil pan. Spoon",
   "Cover with plastic wrap and aluminum foil. Label and freeze.",
   "When ready to cook, thaw in refrigerator 1-2 days. Remove"
  ]
 },
 {
  "id": "five-ingredient-grilled-pork-chops",
  "name": "five ingredient grilled pork chops",
  "box": "freezer",
  "week": 7,
  "category": "main",
  "dish": "skillet",
  "protein": "pork",
  "method": "oven",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "25 minutes",
  "serves": "4-6",
  "calories": 224,
  "ingredients": [
   "4-6 medium-thick pork chops",
   "½ cup soy sauce",
   "2 Tbsps red wine vinegar",
   "2 tsps honey",
   "2 tsps garlic powder"
  ],
  "steps": [
   "In gallon-size zip-top bag, mix soy sauce, red wine vinegar,",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Set grill to high heat and grill 5-8 minutes per side until"
  ]
 },
 {
  "id": "chicken-taco-bowls",
  "name": "chicken taco bowls",
  "box": "freezer",
  "week": 7,
  "category": "main",
  "dish": "mexican",
  "protein": "meatless",
  "method": "slow cooker",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "5-6 hours",
  "serves": "6",
  "calories": 477,
  "ingredients": [
   "1½ lb boneless, skinless",
   "1 large yellow onion, chopped",
   "16 oz jar salsa",
   "15 oz can black beans, rinsed",
   "1 cup frozen corn",
   "1 oz pkg taco seasoning",
   "2 (8.8 oz) pkgs Spanish-style",
   "1 jalapeño, finely chopped",
   "optional toppings: cilantro, diced"
  ],
  "steps": [
   "In gallon-size zip-top bag, combine chicken, onion, salsa,",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Transfer contents of bag to slow cooker. Cover and cook on",
   "Serve chicken mixture over prepared rice with optional"
  ]
 },
 {
  "id": "quick-vegetable-beef-soup",
  "name": "quick vegetable beef soup",
  "box": "freezer",
  "week": 7,
  "category": "main",
  "dish": "soup",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "6-7 hours",
  "serves": "8",
  "calories": 414,
  "ingredients": [
   "2 lb lean ground beef",
   "1 large yellow onion, chopped",
   "2 (12 oz) pkgs frozen",
   "28 oz can crushed tomatoes",
   "8 oz can tomato sauce",
   "1 green bell pepper, chopped",
   "1 pkg dry onion soup mix",
   "½ tsp dried oregano",
   "32 oz carton low-sodium",
   "1 tsp sugar (optional)"
  ],
  "steps": [
   "In large skillet, cook ground beef and onion until beef is",
   "In gallon-size zip-top bag, add beef and remaining ingredients",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag and reserved beef broth into slow cooker."
  ]
 },
 {
  "id": "easy-peasy-baked-ziti",
  "name": "easy peasy baked ziti",
  "box": "freezer",
  "week": 7,
  "category": "main",
  "dish": "pasta",
  "protein": "meatless",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6-8",
  "calories": 279,
  "ingredients": [
   "12 oz ziti pasta",
   "24 oz jar marinara sauce, divided",
   "15 oz carton ricotta cheese",
   "½ cup Parmesan cheese, grated",
   "2 cloves garlic, minced",
   "1 cup mozzarella cheese, shredded"
  ],
  "steps": [
   "Cook ziti according to package directions to al dente.",
   "Spread into 13x9-inch disposable foil pan. Top with remaining",
   "Cover with plastic wrap and aluminum foil. Label and freeze.",
   "When ready to cook, thaw in refrigerator 1-2 days. Remove"
  ]
 },
 {
  "id": "homemade-beef-meatballs",
  "name": "homemade beef meatballs",
  "box": "freezer",
  "week": 8,
  "category": "main",
  "dish": "skillet",
  "protein": "beef",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6",
  "calories": 273,
  "ingredients": [
   "1 lb lean ground beef",
   "2 large eggs, beaten with",
   "½ cup Parmesan cheese, grated",
   "1 cup panko or Italian bread crumbs",
   "1 Tbsp onion powder or 1 small",
   "2-3 cloves garlic, minced",
   "½ tsp dried oregano",
   "1 tsp dried basil",
   "1 tsp Italian seasoning",
   "1 tsp garlic salt",
   "freshly ground pepper to taste",
   "⅛ cup dried parsley"
  ],
  "steps": [
   "In large bowl, mix all ingredients together by hand.",
   "Form into golf ball-size meatballs and place onto",
   "Flash freeze on baking sheet, then place into gallon-size zip-",
   "When ready to cook, thaw in refrigerator 1-2 days. Preheat",
   "Serve alone or with your favorite pasta sauce and spaghetti or"
  ]
 },
 {
  "id": "cheddar-ranch-burgers",
  "name": "cheddar ranch burgers",
  "box": "freezer",
  "week": 8,
  "category": "main",
  "dish": "sandwich",
  "protein": "meatless",
  "method": "oven",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "10 minutes",
  "serves": "6",
  "calories": 285,
  "ingredients": [
   "2 lb ground chuck",
   "1 cup cheddar cheese, shredded",
   "1 oz pkg dry ranch dressing mix",
   "hamburger buns or lettuce leaves"
  ],
  "steps": [
   "Mix beef, cheese, and ranch dressing mix until well combined.",
   "Place into gallon-size zip-top bag with small square of wax",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Grill patties, covered with grill lid, over direct high heat about"
  ]
 },
 {
  "id": "sweet-spicy-barbecue-chicken",
  "name": "sweet & spicy barbecue chicken",
  "box": "freezer",
  "week": 8,
  "category": "main",
  "dish": "skillet",
  "protein": "meatless",
  "method": "slow cooker",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "6-8 hours",
  "serves": "6",
  "calories": 400,
  "ingredients": [
   "2 lb boneless, skinless",
   "2 cups ketchup",
   "¼ cup Worcestershire sauce",
   "3 Tbsps light brown sugar",
   "2 Tbsps chili powder",
   "1 Tbsp hot sauce"
  ],
  "steps": [
   "In gallon-size zip-top bag, place ketchup, Worcestershire",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on"
  ]
 },
 {
  "id": "slow-cooker-cilantro-lime-chicken",
  "name": "slow cooker cilantro lime chicken",
  "box": "freezer",
  "week": 8,
  "category": "main",
  "dish": "skillet",
  "protein": "meatless",
  "method": "slow cooker",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "7-8 hours",
  "serves": "6",
  "calories": 335,
  "ingredients": [
   "1½ lb boneless, skinless",
   "15 oz can black beans, rinsed",
   "10 oz can Ro- Tel tomatoes",
   "1 cup frozen corn kernels",
   "½ cup salsa",
   "½ cup fresh cilantro, chopped",
   "1 large yellow onion, diced",
   "2 tsps ground cumin",
   "2 tsps chili powder",
   "4 cloves garlic, minced",
   "4 Tbsps lime juice",
   "1 jalapeño, diced (optional)"
  ],
  "steps": [
   "In gallon-size zip-top bag, combine all ingredients except",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Serve over rice, tortillas, or tortilla chips, if desired."
  ]
 },
 {
  "id": "incredible-baked-oatmeal",
  "name": "incredible baked oatmeal",
  "box": "freezer",
  "week": 8,
  "category": "main",
  "dish": "skillet",
  "protein": "meatless",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6",
  "calories": 473,
  "ingredients": [
   "3 cups quick oats",
   "½ cup brown sugar",
   "¼ cup white sugar",
   "1 tsp salt",
   "1 tsp baking powder",
   "1 tsp ground cinnamon",
   "½ cup pecans, chopped",
   "½ cup craisins",
   "1 large sweet apple, chopped",
   "2 very ripe bananas, smashed",
   "½ cup coconut oil, melted",
   "2 large eggs, beaten",
   "1 cup milk",
   "cinnamon sugar (optional)"
  ],
  "steps": [
   "In large mixing bowl, combine oats, sugars, salt, baking",
   "Mix oil, eggs, and milk together. Pour over oat mixture and",
   "Pour into greased 8x8-inch disposable foil pan. Cover with",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Remove foil and plastic wrap. Bake",
   "Sprinkle individual servings with cinnamon sugar, if desired."
  ]
 },
 {
  "id": "baked-cheesy-spinach-tortellini",
  "name": "baked cheesy spinach tortellini",
  "box": "freezer",
  "week": 9,
  "category": "main",
  "dish": "pasta",
  "protein": "meatless",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "45 minutes",
  "serves": "6",
  "calories": 345,
  "ingredients": [
   "16 oz pkg cheese tortellini",
   "24 oz jar spaghetti sauce",
   "2 cups fresh spinach, chopped",
   "8 oz Italian-blend cheese, shredded"
  ],
  "steps": [
   "Spray 8x8-inch disposable foil pan with cooking spray.",
   "Boil tortellini according to package directions, until al dente.",
   "Spread thin layer of spaghetti sauce into bottom of foil pan.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Bake, uncovered, 45 minutes or until"
  ]
 },
 {
  "id": "beef-burritos-with-green-chiles",
  "name": "beef burritos with green chiles",
  "box": "freezer",
  "week": 9,
  "category": "main",
  "dish": "mexican",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "8 hours",
  "serves": "10",
  "calories": 653,
  "ingredients": [
   "4 lb boneless chuck roast",
   "2 (15 oz) cans whole green chiles",
   "28 oz can diced tomatoes",
   "1 large yellow onion, chopped",
   "2 cloves garlic, minced",
   "1 tsp salt",
   "3 tsps ground cumin",
   "1 tsp cayenne pepper",
   "burrito-size flour tortillas",
   "optional toppings: shredded"
  ],
  "steps": [
   "Drain chiles, reserving liquid. Coarsely chop chiles; place into",
   "In small bowl, combine garlic, salt, cumin, and cayenne; rub",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place all contents of bag into slow cooker. Cover and cook on",
   "Remove roast; shred with 2 forks. Return to slow cooker;"
  ]
 },
 {
  "id": "simple-beef-ragu",
  "name": "simple beef ragu",
  "box": "freezer",
  "week": 9,
  "category": "main",
  "dish": "skillet",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "8-10 hours",
  "serves": "6",
  "calories": 472,
  "ingredients": [
   "2 lb flank steak or chuck roast",
   "28 oz can crushed tomatoes",
   "1 cup frozen mirepoix blend",
   "4 cloves garlic, minced",
   "2 bay leaves",
   "1 Tbsp sugar",
   "1½ tsps salt",
   "½ tsp dried thyme"
  ],
  "steps": [
   "Combine all ingredients into gallon-size zip-top bag. Knead to",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Shred meat and serve over pasta, rice, baked potatoes,"
  ]
 },
 {
  "id": "chicken-cordon-bleu-soup",
  "name": "chicken cordon bleu soup",
  "box": "freezer",
  "week": 9,
  "category": "main",
  "dish": "soup",
  "protein": "chicken",
  "method": "slow cooker",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "9 hours",
  "serves": "6",
  "calories": 625,
  "ingredients": [
   "2 lb boneless, skinless chicken",
   "1 medium ham bone or ham hock",
   "32 oz carton chicken broth",
   "1½ cups ham, diced",
   "1 large yellow onion, chopped",
   "4 stalks celery, chopped",
   "4 cloves garlic, diced",
   "2 cups water",
   "1 lb pkg gnocchi pasta",
   "1 cup heavy cream",
   "6 oz Swiss cheese, shredded"
  ],
  "steps": [
   "Place first 8 ingredients into a gallon-size zip-top bag.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook",
   "Open slow cooker and add gnocchi. Replace lid and cook",
   "Stir in heavy cream. Serve with shredded Swiss cheese."
  ]
 },
 {
  "id": "tex-mex-beef-enchiladas",
  "name": "tex-mex beef enchiladas",
  "box": "freezer",
  "week": 9,
  "category": "main",
  "dish": "mexican",
  "protein": "beef",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "8",
  "calories": 329,
  "ingredients": [
   "1 lb ground beef, browned",
   "1 large yellow onion, chopped",
   "3 cloves garlic, minced",
   "1 red pepper, diced",
   "4 oz can diced green chiles, drained",
   "15 oz can black beans, rinsed",
   "1 Tbsp chili powder",
   "½ tsp ground paprika",
   "8 taco-size flour tortillas",
   "2 cups enchilada sauce",
   "1-1½ cups cheddar"
  ],
  "steps": [
   "In gallon-size zip-top bag, place browned ground beef, onion,",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into large skillet and cook over",
   "Divide beef filling evenly between 8 flour tortillas. Roll tightly",
   "Preheat oven to 375°F. Bake 30-35 minutes or until sauce is"
  ]
 },
 {
  "id": "easy-meatball-stuffed-shells",
  "name": "easy meatball stuffed shells",
  "box": "freezer",
  "week": 10,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "8",
  "calories": 484,
  "ingredients": [
   "20-24 jumbo pasta shells",
   "15 oz carton ricotta cheese",
   "3 cups mozzarella cheese,",
   "¼ cup Parmesan cheese, grated",
   "2 Tbsps dried parsley flakes",
   "1 tsp Italian seasoning",
   "1 large egg, lightly beaten",
   "32 oz pkg frozen turkey meatballs",
   "2 (24 oz) jars spaghetti sauce"
  ],
  "steps": [
   "Cook pasta shells according to package directions",
   "Mix ricotta, 1 cup mozzarella, Parmesan, parsley, Italian",
   "Stuff shells with cheese mixture and 1 frozen meatball per",
   "When ready to cook, thaw in refrigerator 1-2 days. Remove",
   "Preheat oven to 350°F. Bake 30 minutes or until bubbly."
  ]
 },
 {
  "id": "dill-salmon",
  "name": "dill salmon",
  "box": "freezer",
  "week": 10,
  "category": "main",
  "dish": "skillet",
  "protein": "seafood",
  "method": "oven",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "25 minutes",
  "serves": "6",
  "calories": 400,
  "ingredients": [
   "2 lb salmon filet",
   "½ cup sour cream",
   "½ cup mayonnaise",
   "2 Tbsps dried dill weed",
   "3 cloves garlic, minced",
   "¼ cup lemon juice"
  ],
  "steps": [
   "Place salmon into gallon-size zip-top bag.",
   "In small bowl, combine remaining ingredients. Pour into bag",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Carefully place salmon onto foil-"
  ]
 },
 {
  "id": "slow-cooker-mesquite-roast-carrots",
  "name": "slow cooker mesquite roast & carrots",
  "box": "freezer",
  "week": 10,
  "category": "main",
  "dish": "skillet",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "8 hours",
  "serves": "6",
  "calories": 336,
  "ingredients": [
   "2 lb boneless beef shoulder roast",
   "1-2 lb pkg mini carrots",
   "3 Tbsps extra-virgin olive oil",
   "2 Tbsps red wine vinegar",
   "1 oz packet mesquite marinade"
  ],
  "steps": [
   "In gallon-size zip-top bag, add roast and remaining",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Shred meat and serve."
  ]
 },
 {
  "id": "greek-style-pork-chops",
  "name": "greek-style pork chops",
  "box": "freezer",
  "week": 10,
  "category": "main",
  "dish": "skillet",
  "protein": "pork",
  "method": "oven",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "25 minutes",
  "serves": "6",
  "calories": 374,
  "ingredients": [
   "2 lb boneless pork chops",
   "½ cup extra-virgin olive oil",
   "¼ cup lemon juice",
   "2 cloves garlic, minced",
   "2 Tbsps Dijon mustard",
   "2 Tbsps dried oregano",
   "1 tsp dried thyme",
   "1 tsp pepper",
   "1 tsp dried rosemary"
  ],
  "steps": [
   "Combine all ingredients in gallon-size zip-top bag. Knead to",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Grill, covered, over medium heat about 20-25 minutes or"
  ]
 },
 {
  "id": "hot-roast-beef-sandwiches",
  "name": "hot roast beef sandwiches",
  "box": "freezer",
  "week": 10,
  "category": "main",
  "dish": "sandwich",
  "protein": "beef",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "4",
  "calories": 545,
  "ingredients": [
   "¾ lb roast beef, thinly shaved",
   "1 pkg Hawaiian slider buns",
   "9 slices provolone cheese",
   "¼ cup mayonnaise",
   "1 Tbsp poppy seeds",
   "1 Tbsp spicy mustard",
   "dash Worcestershire sauce",
   "1 Tbsp horseradish"
  ],
  "steps": [
   "In medium bowl, mix mayonnaise, poppy seeds, spicy",
   "Place wrapped sandwiches into two gallon-size zip-top bags.",
   "Remove sandwiches from bags, but keep wrapped in foil.",
   "Preheat oven to 350°F, then bake 20-30 minutes, wrapped"
  ]
 },
 {
  "id": "hawaiian-sweet-roll-sliders",
  "name": "hawaiian sweet roll sliders",
  "box": "freezer",
  "week": 11,
  "category": "main",
  "dish": "sandwich",
  "protein": "pork",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "20 minutes",
  "serves": "6",
  "calories": 508,
  "ingredients": [
   "1 pkg Hawaiian rolls",
   "10 slices Swiss cheese",
   "½ lb deli ham, sliced",
   "½ cup butter, melted",
   "1 tsp poppy seeds",
   "1½ Tbsps Dijon mustard",
   "1 Tbsp Worcestershire sauce"
  ],
  "steps": [
   "Remove rolls from package in one big piece, lay flat, and slice",
   "Layer cheese slices over both sections of sandwiches,",
   "Brush tops of sandwiches with remaining butter sauce. Wrap",
   "When ready to cook, thaw in refrigerator 1-2 days. Preheat"
  ]
 },
 {
  "id": "three-cheese-manicotti",
  "name": "three cheese manicotti",
  "box": "freezer",
  "week": 11,
  "category": "main",
  "dish": "skillet",
  "protein": "meatless",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "45 minutes",
  "serves": "6",
  "calories": 301,
  "ingredients": [
   "24 oz carton cottage cheese",
   "1½ cups mozzarella",
   "2 tsps Italian seasoning",
   "½ tsp garlic salt",
   "¼ tsp pepper",
   "8 oz pkg manicotti",
   "¾ cup Italian-blend",
   "24 oz jar spaghetti sauce"
  ],
  "steps": [
   "Spray bottom of 13x9-inch disposable foil pan thoroughly",
   "In small bowl, mix cottage cheese, mozzarella, Italian",
   "Spoon cheese mixture into uncooked manicotti tubes",
   "When ready to cook, thaw in refrigerator 1-2 days. Remove",
   "Preheat oven to 375°F. Bake at least 45 minutes. Let stand"
  ]
 },
 {
  "id": "slow-cooker-beef-tips-gravy",
  "name": "slow cooker beef tips & gravy",
  "box": "freezer",
  "week": 11,
  "category": "main",
  "dish": "skillet",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "6 hours",
  "serves": "6",
  "calories": 429,
  "ingredients": [
   "2 lb stew meat",
   "1 pkg dry onion soup mix",
   "10.5 oz can cream of celery soup",
   "14 oz can beef stock or broth"
  ],
  "steps": [
   "Combine all ingredients into gallon-size zip-top bag. Gently",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Add contents of bag into slow cooker. Cover and cook",
   "Serve over mashed potatoes, rice, or cauliflower rice."
  ]
 },
 {
  "id": "honey-garlic-chicken-thighs",
  "name": "honey garlic chicken thighs",
  "box": "freezer",
  "week": 11,
  "category": "main",
  "dish": "skillet",
  "protein": "meatless",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "6½ hours",
  "serves": "6",
  "calories": 386,
  "ingredients": [
   "2 lb boneless, skinless",
   "1/3 cup honey",
   "1/3 cup soy sauce",
   "6 cloves garlic, minced",
   "2 Tbsps apple cider vinegar",
   "2 Tbsps Worcestershire sauce",
   "2 tsps olive oil",
   "2 Tbsps cornstarch",
   "3 Tbsps water"
  ],
  "steps": [
   "Add chicken thighs to gallon-size zip-top bag.",
   "In small bowl, mix honey, soy sauce, garlic, apple cider vinegar,",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Mix cornstarch and water; pour into slow cooker. Gently stir;"
  ]
 },
 {
  "id": "hearty-beef-stew",
  "name": "hearty beef stew",
  "box": "freezer",
  "week": 11,
  "category": "main",
  "dish": "soup",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "6-8 hours",
  "serves": "6",
  "calories": 337,
  "ingredients": [
   "2 lb beef chuck roast, cut into",
   "1 large yellow onion, sliced",
   "6 stalks celery, sliced",
   "6 carrots, sliced",
   "2 tsps salt",
   "1 Tbsp sugar",
   "2 cups tomato juice",
   "2 Tbsps cornstarch",
   "2 Tbsps water"
  ],
  "steps": [
   "Place all ingredients except cornstarch and water into gallon-",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Mix cornstarch and 2 tablespoons water; add to slow cooker;"
  ]
 },
 {
  "id": "buffalo-chicken-wings",
  "name": "buffalo chicken wings",
  "box": "freezer",
  "week": 12,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "slow cooker",
  "prep": "5 minutes",
  "cookLabel": "cook",
  "cook": "4-5 hours",
  "serves": "8",
  "calories": 504,
  "ingredients": [
   "4 lb chicken wings, split at joints",
   "1 cup mild buffalo wing sauce",
   "2 Tbsps butter",
   "6 Tbsps honey"
  ],
  "steps": [
   "Combine all ingredients in gallon-size zip-top bag.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Remove wings from slow cooker and place onto foil-lined"
  ]
 },
 {
  "id": "grilled-chicken-kabobs",
  "name": "grilled chicken kabobs",
  "box": "freezer",
  "week": 12,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6",
  "calories": 345,
  "ingredients": [
   "2 lb boneless, skinless chicken",
   "½ cup Italian dressing",
   "¼ cup low-sodium soy sauce",
   "½ cup Worcestershire sauce",
   "2-3 sweet onions, cubed",
   "2-3 colorful peppers, cubed",
   "wooden skewers"
  ],
  "steps": [
   "Cut skewers in half and alternate chicken and vegetables to",
   "In small bowl, combine Italian dressing, soy sauce, and",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Prepare grill to medium heat. Place kabobs onto grill, rotating"
  ]
 },
 {
  "id": "shrimp-fajitas",
  "name": "shrimp fajitas",
  "box": "freezer",
  "week": 12,
  "category": "main",
  "dish": "mexican",
  "protein": "seafood",
  "method": "stovetop",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "15 minutes",
  "serves": "4",
  "calories": 274,
  "ingredients": [
   "¼ cup olive oil",
   "4 cloves garlic, minced",
   "1 Tbsp lime juice",
   "1 Tbsp cajun seasoning",
   "1 lb large shrimp, peeled",
   "2 bell peppers, sliced",
   "1 large yellow onion, sliced",
   "¼ cup fresh cilantro, chopped",
   "1 Tbsp olive oil",
   "1 pkg taco-size flour tortillas",
   "optional toppings: cilantro,"
  ],
  "steps": [
   "In small bowl, combine marinade ingredients. Add shrimp to",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "In medium bowl, pat shrimp dry with paper towels, then add",
   "In large skillet, heat 1 tablespoon olive oil until hot.",
   "Serve in warmed flour tortillas with optional toppings,"
  ]
 },
 {
  "id": "chicken-broccoli-potato-bake",
  "name": "chicken, broccoli & potato bake",
  "box": "freezer",
  "week": 12,
  "category": "main",
  "dish": "casserole",
  "protein": "chicken",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "1 hour 10 minutes",
  "serves": "8",
  "calories": 399,
  "ingredients": [
   "11/2 lb boneless, skinless chicken",
   "4½ cups red potatoes, diced",
   "3 cups broccoli florets",
   "½ cup cooked bacon, crumbled",
   "1/2 large yellow onion, sliced",
   "3 cups cheddar cheese, shredded",
   "1 cup heavy cream (or half-",
   "2 Tbsps butter, chopped",
   "salt and pepper",
   "garlic powder"
  ],
  "steps": [
   "Grease 2 (8x8-inch) disposable foil pans. In both pans, layer",
   "Pour ½ cup heavy cream over each pan and sprinkle each dish",
   "Cover with plastic wrap and aluminum foil. Freeze ½ cup",
   "When ready to cook, thaw in refrigerator 1-2 days. Remove",
   "Preheat oven to 350°F. Bake, covered 1 hour or until chicken"
  ]
 },
 {
  "id": "slow-cooker-pepper-steak",
  "name": "slow cooker pepper steak",
  "box": "freezer",
  "week": 12,
  "category": "main",
  "dish": "skillet",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "8 hours",
  "serves": "8",
  "calories": 415,
  "ingredients": [
   "3 lb chuck roast",
   "1 large yellow onion, sliced",
   "1 large green pepper, cut into",
   "1 large red pepper, cut into",
   "1 cup water",
   "4 cloves garlic, minced",
   "1/3 cup cornstarch",
   "½ cup low-sodium soy sauce",
   "2 tsps sugar"
  ],
  "steps": [
   "In gallon-size zip-top bag, place roast, onion, peppers, 1 cup",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of bag into slow cooker. Cover and cook on",
   "Remove roast from slow cooker, transfer vegetables and",
   "Slice or shred beef, return to slow cooker, add vegetables, and"
  ]
 },
 {
  "id": "caprese-steak-salad",
  "name": "caprese steak salad",
  "box": "freezer-expansion",
  "week": 13,
  "category": "main",
  "dish": "salad",
  "protein": "beef",
  "method": "stovetop",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "20 minutes",
  "serves": "6",
  "calories": 557,
  "ingredients": [
   "6 (6 oz) New York strip steaks",
   "1 cup balsamic vinegar",
   "2 Tbsps olive oil",
   "2 Tbsps honey",
   "3 cloves garlic, minced",
   "1 Tbsp dried thyme",
   "1 Tbsp dried oregano",
   "½ tsp salt",
   "¼ tsp pepper",
   "8 oz ball fresh mozzarella cheese",
   "2 Roma tomatoes, sliced",
   "fresh basil leaves",
   "2 heads Romaine lettuce, chopped",
   "balsamic vinaigrette dressing"
  ],
  "steps": [
   "Add first 9 ingredients to a gallon-size zip-top bag, and knead",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Remove steaks from bag; discard marinade.",
   "In a large skillet, cook steak over medium heat, 5-7 minutes",
   "Top steaks with a slice of mozzarella cheese, tomato and fresh"
  ]
 },
 {
  "id": "thai-peanut-chicken-lettuce-wraps",
  "name": "thai peanut chicken lettuce wraps",
  "box": "freezer-expansion",
  "week": 13,
  "category": "main",
  "dish": "sandwich",
  "protein": "chicken",
  "method": "slow cooker",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "6 hours",
  "serves": "6",
  "calories": 509,
  "ingredients": [
   "2 lbs boneless, skinless chicken",
   "14 oz can unsweetened coconut milk",
   "½ cup creamy peanut butter",
   "2 cloves garlic, minced",
   "1 Tbsp grated ginger",
   "3 Tbsps lime juice",
   "2 Tbsps low-sodium soy sauce",
   "3 Tbsps honey",
   "1 Tbsp toasted sesame oil",
   "2 tsps yellow curry powder",
   "1 tsp ground cumin",
   "1 tsp garam masala",
   "½ tsp red pepper flakes",
   "Romaine lettuce hearts",
   "chopped peanuts",
   "chopped cilantro"
  ],
  "steps": [
   "In a medium bowl, combine coconut milk, peanut butter,",
   "Pour mixture into a gallon-size zip-top bag; add chicken.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Add contents of freezer bag to crockpot. Cover and cook on",
   "Shred or cut chicken into small pieces. Spoon into lettuce"
  ]
 },
 {
  "id": "bacon-wrapped-pork-tenderloin",
  "name": "bacon wrapped pork tenderloin",
  "box": "freezer-expansion",
  "week": 13,
  "category": "main",
  "dish": "sandwich",
  "protein": "pork",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6",
  "calories": 407,
  "ingredients": [
   "2 medium pork tenderloins",
   "12-15 slices bacon",
   "¼ cup packed brown sugar",
   "1 tsp paprika",
   "1 tsp salt",
   "1 tsp pepper",
   "2 tsps onion powder",
   "2 cloves garlic, minced",
   "1 cup barbecue sauce"
  ],
  "steps": [
   "Combine all ingredients except bacon and pork in a small bowl.",
   "Rub seasonings over pork, then wrap with bacon, overlapping",
   "Wrap prepared pork tightly in foil and place into a gallon-size",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 375°F.",
   "Meanwhile, heat a large, oven-safe skillet over",
   "Add thawed pork to pan, seam side down, and sear two",
   "Transfer skillet to oven and roast 20-25 minutes or until",
   "Let tenderloins rest a few minutes before slicing."
  ]
 },
 {
  "id": "chicken-tetrazzini",
  "name": "chicken tetrazzini",
  "box": "freezer-expansion",
  "week": 13,
  "category": "main",
  "dish": "pasta",
  "protein": "chicken",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "45 minutes",
  "serves": "8",
  "calories": 594,
  "ingredients": [
   "8 oz spaghetti noodles, broken",
   "3 Tbsps butter",
   "1 large yellow onion, diced",
   "1 small green bell pepper, chopped",
   "4 cloves garlic, minced",
   "5 1/2 cups diced, cooked chicken",
   "4 cups shredded cheese, divided",
   "2 (10.5 oz) cans cream of chicken",
   "1 soup can milk",
   "1 ½ tsps seasoning salt"
  ],
  "steps": [
   "Cook spaghetti noodles according to package directions until",
   "In a large skillet, melt butter then sauté onion and bell",
   "In a large bowl, thoroughly mix together onion mixture, diced",
   "Transfer mixture to a greased 13x9-inch disposable foil pan.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Remove from refrigerator 30 minutes before baking. Preheat",
   "Bake, uncovered, 30-40 minutes until bubbly. Add remaining"
  ]
 },
 {
  "id": "copycat-egg-bites",
  "name": "copycat egg bites",
  "box": "freezer-expansion",
  "week": 13,
  "category": "breakfast",
  "dish": "breakfast",
  "protein": "pork",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "25 minutes",
  "serves": "6",
  "calories": 281,
  "ingredients": [
   "4 slices bacon, diced",
   "6 large eggs",
   "1 ¼ cups (4% milkfat)",
   "1 ¼ cups shredded Gruyere cheese",
   "2 Tbsps cornstarch",
   "¼ tsp salt",
   "⅛ tsp freshly ground pepper",
   "½ tsp hot sauce, such as Tabasco"
  ],
  "steps": [
   "Bring a pot of water to boil. Preheat oven to 300°F, with",
   "Place a 13x9-inch metal or ceramic baking dish (not silicone)",
   "Cook bacon until crisp; drain on paper towels.",
   "Spray a nonstick muffin pan generously with cooking spray.",
   "Blend eggs, cheeses, cornstarch, salt, pepper and hot sauce",
   "Pour egg mixture into muffin pan, filling each well 3/4 full.",
   "Bake on the middle rack 20-25 minutes until eggs are set and",
   "Remove from oven, and let stand 5 minutes. Use a small",
   "Once cool, label and freeze in an airtight container.",
   "Microwave frozen egg bites on a paper towel 60-90 seconds"
  ]
 },
 {
  "id": "thin-mint-pie",
  "name": "thin mint pie",
  "box": "freezer-expansion",
  "week": 13,
  "category": "dessert",
  "dish": "dessert",
  "protein": "none",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "freeze",
  "cook": "4 hours",
  "serves": "8",
  "calories": 579,
  "ingredients": [
   "6 oz cream cheese, softened",
   "14 oz can sweetened condensed milk",
   "24 chocolate mint cookies, divided",
   "8 oz container whipped topping",
   "1 chocolate or Oreo pie crust",
   "12 drops green food"
  ],
  "steps": [
   "Crush 16 chocolate mint cookies.",
   "In a large bowl, beat cream cheese with an electric mixer until",
   "Gently fold in whipped topping. Spoon into prepared pie crust.",
   "Cover with plastic wrap and aluminum foil. Label, and freeze",
   "Remove from freezer, and set on counter 10 minutes to"
  ]
 },
 {
  "id": "asian-sesame-chicken-salad",
  "name": "asian sesame chicken salad",
  "box": "freezer-expansion",
  "week": 14,
  "category": "main",
  "dish": "salad",
  "protein": "chicken",
  "method": "slow cooker",
  "prep": "30 minutes",
  "cookLabel": "cook",
  "cook": "4 hours",
  "serves": "6",
  "calories": 401,
  "ingredients": [
   "2 lbs boneless, skinless chicken",
   "¼ cup soy sauce",
   "1 Tbsp brown sugar",
   "1 tsp garlic powder",
   "2 tsps sesame oil",
   "3 Romaine lettuce hearts, chopped",
   "15 oz can Mandarin oranges,",
   "½ cup sliced almonds",
   "½ cup cilantro, chopped",
   "3 green onions, sliced",
   "1 ½ cups wonton strips or",
   "2 Tbsps sesame seeds",
   "store bought Asian dressing"
  ],
  "steps": [
   "Add chicken, soy sauce, brown sugar, garlic powder and",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Add contents of freezer bag to slow cooker. Cover and cook",
   "Toss all salad ingredients together, and top with sliced chicken.",
   "Serve with your favorite Asian dressing or follow",
   "In a small saucepan, heat ½ cup rice vinegar, ¼ cup sugar and",
   "Pour into a glass jar, and add 1 tablespoon sesame oil, ¼ cup"
  ]
 },
 {
  "id": "black-bean-enchilada-casserole",
  "name": "black bean enchilada casserole",
  "box": "freezer-expansion",
  "week": 14,
  "category": "main",
  "dish": "mexican",
  "protein": "meatless",
  "method": "oven",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "40 minutes",
  "serves": "4",
  "calories": 506,
  "ingredients": [
   "2 (15 oz) cans black beans, rinsed",
   "1 ¼ cups enchilada sauce, divided",
   "1 cup shredded Mexican-blend",
   "½ tsp ground cumin",
   "8 (6-inch) corn tortillas, divided",
   "optional taco toppings: sour cream,"
  ],
  "steps": [
   "Spray an 8x8-inch disposable foil pan with cooking spray.",
   "In a large bowl, stir together beans, ¾ cup enchilada sauce, ½",
   "Place 4 corn tortillas into the bottom of prepared pan, tearing",
   "Top with half of the bean mixture, and drizzle with ¼ cup",
   "Label, and freeze.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 350°F. Bake casserole, covered, 30",
   "Serve with optional taco toppings, if desired."
  ]
 },
 {
  "id": "chicken-wild-rice-soup",
  "name": "chicken & wild rice soup",
  "box": "freezer-expansion",
  "week": 14,
  "category": "main",
  "dish": "soup",
  "protein": "chicken",
  "method": "slow cooker",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "8-10 hours",
  "serves": "6-8",
  "calories": 278,
  "ingredients": [
   "1 ½ lbs boneless, skinless",
   "2 cloves garlic, minced",
   "1 large yellow onion, diced",
   "2 cups fresh mushrooms, sliced",
   "1 ½ cups celery, diced",
   "1 cup shredded carrots",
   "1 ½ cups wild rice",
   "2 tsps salt",
   "½ tsp pepper",
   "2 tsps garlic powder",
   "½ Tbsp mustard",
   "½ tsp dried thyme",
   "6 cups low-sodium chicken broth",
   "1 ½ cups milk",
   "fresh parsley, for garnish"
  ],
  "steps": [
   "Add all ingredients except chicken broth, milk and parsley to a",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Add contents of bag and 6 cups chicken broth to slow cooker.",
   "Cover and cook on low, 8-10 hours.",
   "After cooking, remove chicken and shred with a fork.",
   "Add 1 ½ cups milk, and pulse with an immersion blender or",
   "Put shredded chicken back into slow cooker, sprinkle with"
  ]
 },
 {
  "id": "barbacoa-bowls",
  "name": "barbacoa bowls",
  "box": "freezer-expansion",
  "week": 14,
  "category": "main",
  "dish": "mexican",
  "protein": "beef",
  "method": "slow cooker",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "9-10 hours",
  "serves": "6",
  "calories": 618,
  "ingredients": [
   "7 oz can chipotle peppers",
   "3 lb boneless beef chuck roast",
   "½ cup apple cider vinegar",
   "½ large yellow onion, diced",
   "1 bay leaf",
   "2 tsps dried oregano",
   "1 tsp salt",
   "1 tsp pepper",
   "4 Tbsps fresh lime juice",
   "½ cup low-sodium beef broth",
   "3 cups cooked white rice",
   "8 oz pkg shredded iceberg lettuce",
   "2 (15 oz) cans pinto beans, drained",
   "1 red onion, diced",
   "1 ½ cups shredded cheddar cheese"
  ],
  "steps": [
   "Dice 2 chipotle peppers from can, and add to a gallon-size",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Add contents of bag to slow cooker along with ½ cup beef",
   "Remove beef and shred. Stir back into slow cooker, cover and",
   "Serve on top of rice, with shredded lettuce, pinto beans,"
  ]
 },
 {
  "id": "blueberry-french-toast-with-vanilla-glaze",
  "name": "blueberry french toast with vanilla glaze",
  "box": "freezer-expansion",
  "week": 14,
  "category": "breakfast",
  "dish": "breakfast",
  "protein": "meatless",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "1 hour",
  "serves": "5",
  "calories": 473,
  "ingredients": [
   "5 large eggs",
   "1 cup milk",
   "¼ cup butter, melted",
   "⅓ cup pure maple syrup",
   "2 tsps vanilla extract",
   "10 oz loaf sourdough bread,",
   "1 ½ cups fresh or frozen",
   "1 Tbsp milk (or more)",
   "½ tsp vanilla extract",
   "pinch of salt",
   "½ cup powdered sugar"
  ],
  "steps": [
   "In a large bowl, whisk together first five ingredients.",
   "Spray 8x8-inch foil pan with cooking spray. Add bread and",
   "Cover with plastic wrap and aluminum foil. Label, and freeze.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Set casserole on counter while oven preheats to 350°F.",
   "To make the vanilla glaze, stir together milk, vanilla and salt in",
   "Let casserole cool about 10 minutes. Use a spoon to drizzle"
  ]
 },
 {
  "id": "frosty-strawberry-squares",
  "name": "frosty strawberry squares",
  "box": "freezer-expansion",
  "week": 14,
  "category": "dessert",
  "dish": "dessert",
  "protein": "none",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "freeze",
  "cook": "6 hours",
  "serves": "12",
  "calories": 319,
  "ingredients": [
   "1 cup flour",
   "½ cup packed brown sugar",
   "½ cup chopped pecans",
   "½ cup butter, melted",
   "2 large egg whites",
   "1 cup white sugar",
   "2 cups diced strawberries",
   "2 Tbsps lemon juice",
   "1 cup heavy cream"
  ],
  "steps": [
   "Preheat oven to 350°F.",
   "Grease a 13x9-inch baking dish or disposable foil pan.",
   "Line a rimmed baking sheet with aluminum foil. In a bowl, stir",
   "In a large bowl, whip egg whites and lemon juice with an electric",
   "In a separate bowl, whip the cream with an electric mixer",
   "Remove from freezer, and set on counter 10-15 minutes to"
  ]
 },
 {
  "id": "coconut-chicken-with-orange-dipping-sauce",
  "name": "coconut chicken with orange dipping sauce",
  "box": "freezer-expansion",
  "week": 15,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "oven",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "35 minutes",
  "serves": "6",
  "calories": 338,
  "ingredients": [
   "1 ½ lbs boneless, skinless chicken",
   "1 large egg, beaten",
   "⅔ cup long or short unsweetened",
   "¼ cup flour",
   "½ tsp garlic powder",
   "½ tsp salt",
   "¼ tsp pepper",
   "½ cup orange marmalade",
   "¼ cup honey",
   "¼ cup Dijon mustard",
   "3-4 drops hot pepper sauce"
  ],
  "steps": [
   "Cut chicken breasts into 1-inch wide strips (or use",
   "Add beaten egg to a shallow bowl. Combine coconut flakes,",
   "Dip both sides of each chicken into egg wash, then coat in",
   "Flash freeze coated, uncooked chicken fingers on a baking",
   "In a small bowl, combine all sauce ingredients together,",
   "When ready to cook, preheat oven to 425°F. Place frozen",
   "Bake 30-35 minutes. Turn chicken at the halfway point",
   "Let sauce thaw on countertop while chicken is cooking.",
   "Serve sauce alongside chicken tenders for dipping."
  ]
 },
 {
  "id": "cheesy-beef-taco-pockets",
  "name": "cheesy beef taco pockets",
  "box": "freezer-expansion",
  "week": 15,
  "category": "main",
  "dish": "mexican",
  "protein": "beef",
  "method": "oven",
  "prep": "25 minutes",
  "cookLabel": "cook",
  "cook": "20 minutes",
  "serves": "6",
  "calories": 642,
  "ingredients": [
   "1 ½ lbs lean ground beef",
   "1 oz pkg taco seasoning",
   "8 oz pkg light cream cheese,",
   "½ cup salsa",
   "1 cup shredded",
   "12 taco-size flour tortillas",
   "2 Tbsps butter, melted"
  ],
  "steps": [
   "In a large skillet, cook ground beef until browned and",
   "Add taco seasoning, and follow package directions to season",
   "In a medium mixing bowl, beat cream cheese until almost",
   "Take a tortilla, and spread a spoonful of the salsa mixture",
   "Fold the tortilla up as you would a burrito, and place onto",
   "Cover baking sheet with plastic wrap or foil, then place into",
   "Once they are frozen enough not to stick to each other,",
   "When ready to serve, preheat oven to 350°F. Place frozen"
  ]
 },
 {
  "id": "chicken-ranch-mac-n-cheese",
  "name": "chicken ranch mac ‘n cheese",
  "box": "freezer-expansion",
  "week": 15,
  "category": "main",
  "dish": "pasta",
  "protein": "pork",
  "method": "stovetop",
  "prep": "25 minutes",
  "cookLabel": "cook",
  "cook": "1 hour",
  "serves": "8",
  "calories": 529,
  "ingredients": [
   "3 cups uncooked elbow macaroni",
   "3 Tbsps butter",
   "2 Tbsps flour",
   "½ tsp salt",
   "¼ tsp pepper",
   "2 cups milk",
   "1 ½ cups shredded cheddar cheese",
   "½ cup grated Parmesan cheese",
   "½ cup shredded Swiss cheese",
   "¾ cup ranch salad dressing",
   "2 cups coarsely chopped",
   "⅓ cup seasoned bread crumbs",
   "2 Tbsps butter, melted",
   "8 slices of bacon, cooked"
  ],
  "steps": [
   "Cook macaroni according to package directions for al dente;",
   "Meanwhile, in a medium saucepan, melt butter over medium",
   "Add chicken and sauce to macaroni, tossing to combine.",
   "Toss bread crumbs with melted butter; sprinkle over",
   "When ready to cook, partially thaw in refrigerator overnight.",
   "Remove from refrigerator 30 minutes before baking. Preheat"
  ]
 },
 {
  "id": "taco-soup",
  "name": "taco soup",
  "box": "freezer-expansion",
  "week": 15,
  "category": "main",
  "dish": "soup",
  "protein": "beef",
  "method": "stovetop",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "20 minutes",
  "serves": "6",
  "calories": 315,
  "ingredients": [
   "1 lb lean ground beef",
   "10 oz can Ro-tel tomatoes",
   "15 oz can dark red kidney beans,",
   "15 oz can ranch style beans",
   "11 oz can shoepeg corn",
   "1 ½ cups water",
   "1 oz pkg taco seasoning",
   "1 oz pkg ranch dressing mix",
   "1 cup shredded"
  ],
  "steps": [
   "In a large skillet, cook ground beef until browned and crumbly;",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Pour soup contents into a large stock-pot. Turn heat to",
   "Sprinkle with cheese to serve."
  ]
 },
 {
  "id": "easy-breakfast-sandwich",
  "name": "easy breakfast sandwich",
  "box": "freezer-expansion",
  "week": 15,
  "category": "breakfast",
  "dish": "breakfast",
  "protein": "pork",
  "method": "oven",
  "prep": "15 minutes",
  "cookLabel": "cook",
  "cook": "25 minutes",
  "serves": "12",
  "calories": 284,
  "ingredients": [
   "12 large eggs",
   "2 Tbsps milk",
   "1 ½ tsps salt",
   "½ tsp pepper",
   "12 slices Swiss cheese",
   "12 slices Canadian bacon",
   "12 whole-wheat English muffins"
  ],
  "steps": [
   "Grease a 13x9-inch baking dish well, and preheat oven",
   "Beat eggs, milk, salt and pepper using an electric mixer",
   "Pour into baking dish, and bake 18-22 minutes until eggs are",
   "Let cool, then cut into 12 squares.",
   "For sandwiches, add cheese, egg and Canadian bacon to",
   "Wrap in parchment paper or foil. Label, and freeze in a couple",
   "To cook, remove paper, and wrap in a slightly dampened",
   "Defrost in microwave one minute, turning halfway through.",
   "Microwave 30-60 seconds on regular power, being careful"
  ]
 },
 {
  "id": "apple-pie-a-la-mode",
  "name": "apple pie à la mode",
  "box": "freezer-expansion",
  "week": 15,
  "category": "dessert",
  "dish": "dessert",
  "protein": "none",
  "method": "oven",
  "prep": "1 hour",
  "cookLabel": "freeze",
  "cook": "4 hours",
  "serves": "8",
  "calories": 443,
  "ingredients": [
   "21 oz can apple pie filling",
   "1 graham cracker crust",
   "2 cups butter pecan",
   "12 oz jar caramel ice cream",
   "½ cup chopped, toasted"
  ],
  "steps": [
   "Spread half of pie filling over crust. Top with half of the ice",
   "Drizzle with half of the caramel topping, ¼ cup pecans then",
   "Spread remaining ice cream over top. Cover with plastic wrap",
   "Remove from freezer 30 minutes before serving.",
   "In a microwave, warm remaining caramel topping.",
   "Serve pie with warm caramel topping, and sprinkle with"
  ]
 },
 {
  "id": "baked-cheese-bacon-grits",
  "name": "baked cheese & bacon grits",
  "box": "freezer-expansion",
  "week": 16,
  "category": "breakfast",
  "dish": "breakfast",
  "protein": "chicken",
  "method": "oven",
  "prep": "30 minutes",
  "cookLabel": "cook",
  "cook": "1 hour",
  "serves": "8",
  "calories": 500,
  "ingredients": [
   "6-8 slices of bacon, chopped",
   "3 cups water",
   "3 cups chicken stock",
   "1 tsp garlic powder",
   "¼ tsp salt",
   "½ tsp pepper",
   "2 cups quick-cooking grits",
   "12 oz Velveeta cheese, cubed",
   "½ cup butter, cubed",
   "½ cup milk",
   "4 large eggs, room temperature,",
   "2 cups shredded white"
  ],
  "steps": [
   "In a large saucepan, cook bacon over medium heat until crisp,",
   "Add water, stock, garlic powder, salt and pepper to bacon",
   "Reduce heat to medium-low; cook, covered, 5-7 minutes or",
   "Add Velveeta and butter; stir until melted. Stir in milk, and",
   "Transfer to a greased 13x9-inch disposable foil pan. Sprinkle",
   "Cool casserole; cover with plastic wrap and aluminum foil.",
   "When ready to serve, partially thaw in refrigerator overnight.",
   "Preheat oven to 350°F. Bake, uncovered, 50-60 minutes or"
  ]
 },
 {
  "id": "chicken-a-la-king",
  "name": "chicken à la king",
  "box": "freezer-expansion",
  "week": 16,
  "category": "main",
  "dish": "skillet",
  "protein": "chicken",
  "method": "slow cooker",
  "prep": "30 minutes",
  "cookLabel": "cook",
  "cook": "6-8 hours",
  "serves": "8",
  "calories": 501,
  "ingredients": [
   "2 ½ lbs boneless, skinless",
   "½ large yellow onion, diced",
   "1 green bell pepper, diced",
   "2 stalks celery, diced",
   "8 oz pkg fresh mushrooms, sliced",
   "3 cloves garlic, minced",
   "½ tsp salt",
   "1 tsp pepper",
   "2 (10.5 oz) cans cream of",
   "2 cups low-sodium chicken broth",
   "8 oz pkg cream cheese, diced",
   "¼ cup water",
   "2 Tbsps cornstarch",
   "2 cups frozen peas",
   "8-count can jumbo biscuits"
  ],
  "steps": [
   "In a small bowl, mix together cream of chicken soup and",
   "Add to a gallon-size zip-top bag, along with remaining",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Add contents of bag to slow cooker. Cover and cook on low",
   "Shred chicken, and return to crockpot.",
   "Stir together water and cornstarch; mix into crockpot with",
   "Cover and cook on low an additional 30 minutes or on high",
   "In the meantime, cook biscuits according to package directions.",
   "Serve by cutting biscuits in half and topping with desired"
  ]
 },
 {
  "id": "slow-cooker-cajun-gumbo",
  "name": "slow cooker cajun gumbo",
  "box": "freezer-expansion",
  "week": 16,
  "category": "main",
  "dish": "soup",
  "protein": "seafood",
  "method": "slow cooker",
  "prep": "10 minutes",
  "cookLabel": "cook",
  "cook": "4-6 hours",
  "serves": "6",
  "calories": 535,
  "ingredients": [
   "2 lbs boneless, skinless chicken",
   "12 oz pkg andouille sausage,",
   "1 green bell pepper, diced",
   "½ large yellow onion, diced",
   "2 stalks celery, diced",
   "2 cloves garlic, minced",
   "1 cup frozen or fresh sliced okra",
   "6 oz can tomato paste",
   "15 oz can diced tomatoes",
   "4 tsps Cajun (or Creole) seasoning",
   "1 bay leaf",
   "1 lb uncooked large shrimp, peeled",
   "2 cups cooked rice"
  ],
  "steps": [
   "Add all ingredients except shrimp and rice to a gallon-size zip-",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Place contents of gumbo bag into slow cooker. Stir to mix",
   "Stir in shrimp. Cover, and cook an additional 5-10 minutes or",
   "Serve over warmed rice."
  ]
 },
 {
  "id": "german-meatballs",
  "name": "german meatballs",
  "box": "freezer-expansion",
  "week": 16,
  "category": "main",
  "dish": "skillet",
  "protein": "beef",
  "method": "stovetop",
  "prep": "20 minutes",
  "cookLabel": "cook",
  "cook": "25 minutes",
  "serves": "8",
  "calories": 361,
  "ingredients": [
   "1 lb lean ground beef",
   "1 lb ground pork",
   "½ cup finely chopped yellow onion",
   "1 cup fine dry bread crumbs",
   "2 Tbsps snipped fresh parsley",
   "2 tsps salt",
   "¼ tsp pepper",
   "1 ½ tsps Worcestershire sauce",
   "2 large eggs, beaten",
   "½-¾ cup milk",
   "2-3 Tbsps vegetable oil",
   "32 oz jar sauerkraut, undrained"
  ],
  "steps": [
   "In a large bowl, combine first 10 ingredients; shape into 24",
   "Heat oil in a large skillet; add meatballs and brown on all sides.",
   "Remove meatballs and drain fat.",
   "Spoon sauerkraut into skillet, then place meatballs over top.",
   "Cover and simmer 15-20 minutes or until meatballs are",
   "Allow everything to cool, then transfer to a gallon-size zip-top",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Reheat in a covered skillet until heated through. Or place into"
  ]
 },
 {
  "id": "chicken-rice-bake",
  "name": "chicken & rice bake",
  "box": "freezer-expansion",
  "week": 16,
  "category": "main",
  "dish": "casserole",
  "protein": "chicken",
  "method": "oven",
  "prep": "25 minutes",
  "cookLabel": "cook",
  "cook": "30 minutes",
  "serves": "6",
  "calories": 442,
  "ingredients": [
   "2–3 Tbsps olive oil, divided",
   "½ large yellow onion, diced",
   "2 large carrots, finely chopped",
   "2–3 stalks celery, finely chopped",
   "2 cups finely chopped broccoli",
   "2 cloves garlic, minced",
   "1 tsp poultry seasoning",
   "1 tsp Italian seasoning",
   "salt and pepper",
   "2 cups cooked chicken, diced",
   "2 cups cooked rice",
   "1 cup sour cream",
   "1 ½ cups low-sodium chicken broth",
   "½ cup freshly grated",
   "2 cups shredded cheddar cheese"
  ],
  "steps": [
   "In a large skillet, heat 1-2 tablespoons oil over medium-high",
   "In a large mixing bowl, whisk together sour cream and chicken",
   "Spray a 13x9-inch disposable foil pan with cooking spray.",
   "When ready to cook, thaw in refrigerator 1-2 days.",
   "Preheat oven to 375°F. Remove foil and plastic wrap. Bake"
  ]
 },
 {
  "id": "chocolate-icebox-cake",
  "name": "chocolate icebox cake",
  "box": "freezer-expansion",
  "week": 16,
  "category": "dessert",
  "dish": "dessert",
  "protein": "none",
  "method": "no-cook",
  "prep": "15 minutes",
  "cookLabel": "freeze",
  "cook": "4+ hours",
  "serves": "12",
  "calories": 566,
  "ingredients": [
   "8 oz pkg cream cheese, softened",
   "5.9 oz box instant chocolate pudding",
   "2 ½ cups milk",
   "8 oz container whipped",
   "14.4 oz box chocolate",
   "1 cup heavy whipping cream",
   "3 cups semi-sweet chocolate chips"
  ],
  "steps": [
   "Using a mixer, beat softened cream cheese in a large bowl",
   "Slowly pour in milk, and mix until minimal lumps are left; fold",
   "Spread ½ cup pudding mixture onto the bottom of a 13x9-inch",
   "To make the ganache, microwave heavy whipping cream",
   "Pour half of the remaining pudding mixture on top of the",
   "Let cool and cover with plastic wrap and aluminum foil.",
   "Label, and freeze 4 hours or overnight. Remove from freezer,"
  ]
 }
];
